defaults:
  - benchmark: inference # default benchmark
  - experiment # inheriting from experiment config
  - _self_ # for hydra 1.1 compatibility
  - override hydra/job_logging: colorlog # colorful logging
  - override hydra/hydra_logging: colorlog # colorful logging

hydra:
  run:
    dir: ???
  job:
    chdir: true
    env_set:
      CUDA_VISIBLE_DEVICES: 0
      CUDA_DEVICE_ORDER: PCI_BUS_ID

model: ???
experiment_name: ???

backend:
  initial_isolation_check: true
  continous_isolation_check: true

benchmark:
  duration: 10
  memory: true
  energy: true

  new_tokens: 1000
  input_shapes:
    batch_size: 1
    sequence_length: 256

hub_kwargs:
  trust_remote_code: true