defaults:
  - backend: pytorch
  - _base_ # inheriting from base config
  - _self_ # for hydra 1.1 compatibility

experiment_name: pytorch+cuda+float16+awq-4bit+gemv
device: cuda

backend:
  no_weights: true
  torch_dtype: float16
  quantization_scheme: awq
  quantization_config:
    bits: 4
    version: gemv
    do_fuse: false
