defaults:
  - backend: pytorch
  - _base_ # inheriting from base config
  - _self_ # for hydra 1.1 compatibility

experiment_name: pytorch+cuda+float16+gptq-4bit+exllama-v1
device: cuda

backend:
  no_weights: true
  torch_dtype: float16
  quantization_scheme: gptq
  quantization_config:
    bits: 4
    use_cuda_fp16: false
    use_exllama: true
    exllama_config:
      version: 1
