# name: Update LLM-Perf

# on:
#   push:
#     branches:
#       - main
#   schedule:
#     # every 6 hours
#     - cron: "0 */6 * * *"

# concurrency:
#   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
#   cancel-in-progress: true

# jobs:
#   build-and-test:
#     runs-on: self-hosted
#     steps:
#       - name: Restore files ownership
#         run: docker run
#           --rm
#           --entrypoint /bin/bash
#           --env HOST_UID=`id -u`
#           --env HOST_GID=`id -g`
#           --volume $(pwd):/workspace/llm-perf-backend
#           --workdir /workspace/llm-perf-backend
#           ubuntu
#           -c 'chown -R ${HOST_UID}:${HOST_GID} /workspace/llm-perf-backend'

#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Run benchmarks
#         run: docker run
#           --rm
#           --entrypoint /bin/bash
#           --gpus '"device=0,1,2,4"'
#           --volume $(pwd):/workspace/llm-perf-backend
#           --workdir /workspace/llm-perf-backend
#           optimum-benchmark-gpu
#           -c 'sh run_on_dgx.sh'