name: Update Open-LLM file

on:
  workflow_dispatch:
  schedule:
    # Every day at 00:00 UTC
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  update_open_llm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Cloning Weyaxi's Open-LLM Leaderboard scrapper
        run: |
          git clone https://github.com/Weyaxi/scrape-open-llm-leaderboard.git

      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install pandas transformers
          pip install -r scrape-open-llm-leaderboard/requirements.txt

      - name: Run Weyaxi's Open-LLM Leaderboard scrapper
        run: |
          python scrape-open-llm-leaderboard/main.py

      - name: Update Open-LLM Leaderboard models list
        run: |
          python scripts/update_open_llm.py
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
